# Generated by Django 3.2 on 2023-10-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20231003_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('gr', 'Grams'), ('kg', 'Kilogram'), ('L', 'Litres'), ('mL', 'Millilitres'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('pieces', 'Pieces'), ('slices', 'Slices')], default='gr', max_length=100),
        ),
    ]
