# Generated by Django 3.2 on 2023-10-12 17:29

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='estimated_time',
            field=models.PositiveIntegerField(validators=[blog.models.validate_nonzero], verbose_name='estimated_time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(validators=[blog.models.validate_nonzero], verbose_name='servings'),
        ),
    ]
